#!/usr/bin/env bash

#  screenshooter
#
#  updates: github.com/tagirov/bin
#  deps:    ffmpeg, xclip, gimp

## replace for external process [github.com/dylanaraps/pure-bash-bible]
_sleep() {
    read -rt "$1" <> <(:) || :
}

scr_dir=~/pics/screen/

date=$(date +%F)
time=$(date +"%H-%M-%S")
file="$scr_dir/$date-$time.jpg"

ffmpeg              \
    -y              \
    -hide_banner    \
    -loglevel error \
    -f x11grab      \
    -i :0.0         \
    -vframes 1      \
    -q:v 0          \
    "$file"

## copy image to clipboard
if [ "$1" == "c" ]; then
    xclip -selection clipboard -t image/png < "$file"
    rm $file
fi

## save to folder and open in gimp
if [ "$1" == "g" ]; then
    gimp $file
    _sleep 1  ## the file will be deleted before gimp opens it if gimp is already launched
    rm $file
fi
